projects:
  werewolvesiographql-dev:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: a4wh6b43szcq3actpxbkejfotq
        maxDepth: 3
extensions:
  amplify:
    version: 3
